nodeLinker: pnp

npmScopes:
  bfi-finance:
    npmAuthToken: "${GH_PACKAGE_READ_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com/"

yarnPath: .yarn/releases/yarn-4.2.2-git.20240512.hash-8504172.cjs
